name: master-nlp

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python==3.10
  - conda-forge::pandas==2.1.2
  - conda-forge::scikit-learn==1.3.2
  - conda-forge::seaborn==0.13.0
  - conda-forge::transformers==4.35.0
  - conda-forge::datasets==2.14.7
  - conda-forge::pymongo==4.6.0
  - conda-forge::python-dotenv==1.0.0
  - conda-forge::jupyterlab==4.0.8
  - conda-forge::sentence-transformers==2.2.2
  - pytorch::pytorch==2.1.0
  - pytorch::pytorch-cuda